spring:
  application:
    name: ticketing

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# ?? ???? ??
concert:
  reservation:
    timeout: 600  # 10?
  max-seats-per-user: 4
  queue:
    max-size: 10000

jwt:
  expiration: 86400000  # 24??